-sv
+incdir+$UVM_HOME/src
+incdir+../src
+incdir+../sim_uvm
$UVM_HOME/src/uvm_pkg.sv
../sim_uvm/top_tb.sv
../src/async_fifo.v
../src/fifo_mem.v
../src/gray_sync2d.v
../src/rptr_empty.v
../src/wptr_full.v
